### ISSUE TITLE
Root?

### ISSUE THREAD

**Issue by demur1** [BabySoror/Discord-Bot#1]
Se necesita root para tener una mejor experiencia a la hora de crear el bot con Termux?
![IMG_20211110_092544](https://user-images.githubusercontent.com/84679848/141608776-f94044e5-6d34-4393-8d5e-79765160102c.jpg)

**Comment by BabySoror** [comment]
@demur1 
No se nesesita root para crear uno de discord ya solo se nesesita root aveces en algunas limitaciones de termux
